name: Keptn Send Event
on: [push]
  
jobs:
  send_keptn_event:
    runs-on: ubuntu-latest
    name: Sends Keptn Events
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Send Keptn Event
      id: send-keptn-event
      uses: keptn/gh-action-send-event@main
      with:
        keptnApiUrl: ${{ secrets.KEPTN_API_URL }}
        keptnApiToken: ${{ secrets.KEPTN_API_TOKEN }}
        event: |
          {
            "data": {
              "configurationChange": {
                "values": {
                  "image": "docker.io/mongo:4.2.2"
                }
              },
              "deployment": {
                "deploymentURIsLocal": null,
                "deploymentstrategy": ""
              },
              "project": "sockshop",
              "service": "carts-db",
              "stage": "dev"
            },
            "id": "",
            "source": "https://github.com/keptn/keptn/cli#configuration-change",
            "specversion": "1.0",
            "time": "",
            "type": "sh.keptn.event.dev.delivery-direct.triggered",
            "shkeptncontext": ""
          }
        

