name: Keptn Send Event
on: [push]
  
jobs:
  send_keptn_event:
    runs-on: ubuntu-latest
    name: Sends Keptn Events
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Send Keptn Event
      id: send-keptn-event
      uses: keptn/gh-action-send-event@main
      with:
        keptnApiUrl: ${{ secrets.KEPTN_API_URL }}
        keptnApiToken: ${{ secrets.KEPTN_API_TOKEN }}
        

