name: Keptn Send Event
on: [push]
  
jobs:
  send_keptn_event:
    runs-on: ubuntu-latest
    name: Sends Keptn Events
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Send Keptn Event
      id: send-keptn-event
      uses: keptn/gh-action-send-event@feature/implement-action # use ./ to test locally
      env:
        KEPTN_API_URL: ${{ secrets.KEPTN_API_URL }}
        KEPTN_API_TOKEN: ${{ secrets.KEPTN_API_TOKEN }}
      with:
        event: |
          {
            "data": {
              "configurationChange": {
                "values": {
                  "image": "docker.io/mongo:4.2.2"
                }
              },
              "deployment": {
                "deploymentURIsLocal": null,
                "deploymentstrategy": "direct"
              },
              "message": "",
              "project": "sockshop2",
              "result": "",
              "service": "carts-db",
              "stage": "dev",
              "status": ""
            },
            "id": "bff4a822-fce0-45ec-9f48-d895e4008982",
            "source": "gh",
            "specversion": "1.0",
            "type": "sh.keptn.event.dev.delivery.triggered",
            "shkeptnspecversion": "0.2.1"
          }

