name: Keptn Send Event
on: [push]
  
jobs:
  send_keptn_event:
    runs-on: ubuntu-latest
    name: Sends Keptn Events
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Send Keptn Event
      id: send-keptn-event
      uses: keptn/gh-action-send-event@feature/implement-action
      with:
        keptnApiUrl: ${{ secrets.KEPTN_API_URL }}
        keptnApiToken: ${{ secrets.KEPTN_API_TOKEN }}
        event: |
          {
            "data": {
              "configurationChange": {
                "values": {
                  "image": "docker.io/mongo:4.2.2"
                }
              },
              "deployment": {
                "deploymentURIsLocal": null,
                "deploymentstrategy": ""
              },
              "project": "sockshop",
              "service": "carts-db",
              "stage": "dev"
            },
            "id": "64c55e3c-37a3-447a-88e0-e0c0d8d37272",
            "source": "https://github.com/keptn/keptn/cli#configuration-change",
            "specversion": "1.0",
            "time": "2021-04-27T10:18:02.329Z",
            "type": "sh.keptn.event.dev.delivery-direct.triggered",
            "shkeptncontext": "ae332c6a-2281-455b-9f8e-38769f58f0ed"
          }

